site_name: Didaktra - znanje koje ostaje
theme: 
  name: material
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Tamni način rada
      primary: deep purple 
      accent: deep purple
    # Dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Svijetli način rada
      primary: deep purple
      accent: deep purple
  language: hr
  font:
    text: Roboto
  icon:
    logo: material/school-outline
    favicon: images/school-outline.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - navigation.footer
# plugins:
#     - blog    
nav:
  - index.md
  - kako_radimo.md
  - cjenik.md
  - kontakt.md
  # - linkovi.md
  # - Blog:
  #   - blog/index.md
not_in_nav: |
  /hvala.md
  /placanje.md  
markdown_extensions: # latex
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/force-light-mode.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js 

extra_css:
  - styles/form.css

copyright: DIDAKTRA, obrt za poduke i edukaciju. Sva prava pridržana. &copy 2026.